### ISSUE TITLE
New tsinfer version cannot match UKB against TGP ancestors

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#292]
When we use the tree sequence as inferred using the most recent tsinfer version as an ancestors TS, using `tsutil`'s [combine-ukbb-1kg](https://github.com/mcveanlab/treeseq-inference/blob/0cbbb062c96ad4433d8b4d0f120f93ac2d985345/human-data/tsutil.py#L130) command, we get a `-18` library error. Note that the `combine-ukbb-1kg` script runs fine: it's the `match_samples` stage that fails, as follows:

```
2020-07-14 22:56:42,561 [116485] INFO     tsinfer.formats: Loaded SampleData(num_samples=974594, num_sites=15721)
2020-07-14 22:56:42,561 [116485] INFO     tsinfer.cli: Loading ancestral genealogies from 1kg_ukbb_chr20.ancestors.trees
2020-07-14 22:57:06,019 [116485] CRITICAL root: Traceback (most recent call last):
  File "/users/mcvean/yanwong/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/users/mcvean/yanwong/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/users/mcvean/yanwong/miniconda3/lib/python3.7/site-packages/tsinfer/__main__.py", line 9, in <module>
    main()
  File "/users/mcvean/yanwong/miniconda3/lib/python3.7/site-packages/tsinfer/__main__.py", line 5, in main
    cli.tsinfer_main()
  File "/users/mcvean/yanwong/miniconda3/lib/python3.7/site-packages/tsinfer/cli.py", line 567, in tsinfer_main
    args.runner(args)
  File "/users/mcvean/yanwong/miniconda3/lib/python3.7/site-packages/tsinfer/cli.py", line 294, in run_match_samples
    progress_monitor=progress_monitor,
  File "/users/mcvean/yanwong/miniconda3/lib/python3.7/site-packages/tsinfer/inference.py", line 428, in match_samples
    progress_monitor=progress_monitor,
  File "/users/mcvean/yanwong/miniconda3/lib/python3.7/site-packages/tsinfer/inference.py", line 1007, in __init__
    self.restore_tree_sequence_builder()
  File "/users/mcvean/yanwong/miniconda3/lib/python3.7/site-packages/tsinfer/inference.py", line 1057, in restore_tree_sequence_builder
    mutation_site, mutations.node, derived_state, mutations.parent
_tsinfer.LibraryError: Error occured: -18
```

This looks like the error is in self.tree_sequence_builder.restore_mutations(), so I'm wondering if this function doesn't like having multiple mutations at a site (but then how would it work normally?). This is stopping @awohns carrying out matching against UKB using the new tsinfer codebase.

**Comment by hyanwong** [comment]
Oh, I see we have `lib/err.h:#define TSI_ERR_BAD_MUTATION_DUPLICATE_NODE                         -18` which indicates the issue is [here](https://github.com/tskit-dev/tsinfer/blob/d3dc50497bfce920e7d50258cfd32b8310168625/lib/tree_sequence_builder.c#L404).

**Comment by jeromekelleher** [comment]
Hmm, so it looks like there's a bunch of mutations on the same branch? Not sure how this would happen.

**Comment by hyanwong** [comment]
I'm investigating - will print out the site & node number, then triage using the Python API.

**Comment by hyanwong** [comment]
To follow up here, the site in the inferred tree sequence is this:

```
{'id': 1780, 'position': 191809.0, 'ancestral_state': 'C', 'mutations': [{'id': 3942, 'site': 1780, 'node': 618733, 'time': nan, 'derived_state': 'T', 'parent': -1, 'metadata': b''}, {'id': 3943, 'site': 1780, 'node': 518552, 'time': nan, 'derived_state': 'T', 'parent': -1, 'metadata': b''}, {'id': 3944, 'site': 1780, 'node': 430860, 'time': nan, 'derived_state': 'T', 'parent': -1, 'metadata': b''}, {'id': 3945, 'site': 1780, 'node': 304564, 'time': nan, 'derived_state': 'T', 'parent': -1, 'metadata': b''}, {'id': 3946, 'site': 1780, 'node': 228476, 'time': nan, 'derived_state': 'T', 'parent': -1, 'metadata': b''}, {'id': 3947, 'site': 1780, 'node': 111921, 'time': nan, 'derived_state': 'C', 'parent': 3945, 'metadata': b''}, {'id': 3948, 'site': 1780, 'node': 127557, 'time': nan, 'derived_state': 'C', 'parent': 3945, 'metadata': b''}, {'id': 3949, 'site': 1780, 'node': 129023, 'time': nan, 'derived_state': 'T', 'parent': -1, 'metadata': b''}, {'id': 3950, 'site': 1780, 'node': 2022, 'time': nan, 'derived_state': 'T', 'parent': -1, 'metadata': b''}, {'id': 3951, 'site': 1780, 'node': 2196, 'time': nan, 'derived_state': 'T', 'parent': -1, 'metadata': b''}, {'id': 3952, 'site': 1780, 'node': 4143, 'time': nan, 'derived_state': 'C', 'parent': 3949, 'metadata': b''}, {'id': 3953, 'site': 1780, 'node': 4380, 'time': nan, 'derived_state': 'T', 'parent': -1, 'metadata': b''}], 'metadata': b'{"ID": "rs6074579", "REF": "C"}'}
```

But after running `tsutil.py combine-ukbb-1kg`, it becomes the following site:

```
{'id': 15, 'position': 191809.0, 'ancestral_state': '0', 'mutations': [{'id': 83, 'site': 15, 'node': 474160, 'time': nan, 'derived_state': 'T', 'parent': -1, 'metadata': b''}, {'id': 84, 'site': 15, 'node': 412806, 'time': nan, 'derived_state': 'T', 'parent': -1, 'metadata': b''}, {'id': 85, 'site': 15, 'node': 347302, 'time': nan, 'derived_state': 'T', 'parent': -1, 'metadata': b''}, {'id': 86, 'site': 15, 'node': 192105, 'time': nan, 'derived_state': 'T', 'parent': -1, 'metadata': b''}, {'id': 87, 'site': 15, 'node': 2039, 'time': nan, 'derived_state': 'T', 'parent': -1, 'metadata': b''}, {'id': 88, 'site': 15, 'node': 81279, 'time': nan, 'derived_state': 'C', 'parent': -1, 'metadata': b''}, {'id': 89, 'site': 15, 'node': 94151, 'time': nan, 'derived_state': 'C', 'parent': -1, 'metadata': b''}, {'id': 90, 'site': 15, 'node': 4144, 'time': nan, 'derived_state': 'T', 'parent': -1, 'metadata': b''}, {'id': 91, 'site': 15, 'node': 2023, 'time': nan, 'derived_state': 'T', 'parent': -1, 'metadata': b''}, {'id': 92, 'site': 15, 'node': 2197, 'time': nan, 'derived_state': 'T', 'parent': -1, 'metadata': b''}, {'id': 93, 'site': 15, 'node': 4144, 'time': nan, 'derived_state': 'C', 'parent': -1, 'metadata': b''}, {'id': 94, 'site': 15, 'node': 4381, 'time': nan, 'derived_state': 'T', 'parent': -1, 'metadata': b''}], 'metadata': b''}
```

Note that not only are there two mutations at the same site above node 4144, but the ancestral state is marked as '0' whereas the derived states are 'T' or 'C', so something funky is going on.

**Comment by hyanwong** [comment]
We get multiple mutations at the same site above the same node when we perform `simplify(reduce_to_site_topology=True, filter_sites=False)`

**Comment by hyanwong** [comment]
AH - and the reason is that the ancient samples that Wilder inserted into the tree sequence don't have the NODE_IS_SAMPLE bit set (although they do have the NODE_IS_SAMPLE_ANCESTOR set), so they get removed with *any* simplify.

**Comment by hyanwong** [comment]
I realise I closed this too early. It's still an issue in the old UKB pipeline.
