### ISSUE TITLE
tsinfer crash on UK-BB data

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#48]
I guess you might need more info, but I've just had tsinfer crash with

```
 CRITICAL root: Traceback (most recent call last):
  File "/gpfs1/well/mcvean/ukbb12788/miniconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/gpfs1/well/mcvean/ukbb12788/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/gpfs1/well/mcvean/ukbb12788/miniconda3/lib/python3.6/site-packages/tsinfer/__main__.py", line 9, in <module>
    main()
  File "/gpfs1/well/mcvean/ukbb12788/miniconda3/lib/python3.6/site-packages/tsinfer/__main__.py", line 5, in main
    cli.tsinfer_main()
  File "/gpfs1/well/mcvean/ukbb12788/miniconda3/lib/python3.6/site-packages/tsinfer/cli.py", line 366, in tsinfer_main
    args.runner(args)
  File "/gpfs1/well/mcvean/ukbb12788/miniconda3/lib/python3.6/site-packages/tsinfer/cli.py", line 149, in run_infer
    sample_data, progress_monitor=progress_monitor, num_threads=args.num_threads)
  File "/gpfs1/well/mcvean/ukbb12788/miniconda3/lib/python3.6/site-packages/tsinfer/inference.py", line 102, in infer
    path_compression=path_compression, progress_monitor=progress_monitor)
  File "/gpfs1/well/mcvean/ukbb12788/miniconda3/lib/python3.6/site-packages/tsinfer/inference.py", line 255, in match_samples
    manager.match_samples()
  File "/gpfs1/well/mcvean/ukbb12788/miniconda3/lib/python3.6/site-packages/tsinfer/inference.py", line 804, in match_samples
    sample_id, left, right, parent, compress=self.path_compression)
_tsinfer.LibraryError: Error occured: -2
```

**Comment by hyanwong** [comment]
Some more info. This happens at

`ms-paths (5/6)  6%|#####                                                             | 58.3k/975k [8:32:57, 1.94it/s]`

i.e. the ~58300th iteration through the chr20 samples file, as generated by `src/bgen_to_samples.py -chr 20` (script in the treeseq-inference repo). I will try to replicate.

**Comment by jeromekelleher** [comment]
Looking at this, it turns out err=-2 means we ran out of memory, which is basically exactly what we expect to happen. So, other than the crappy error message, this isn't a bug I think. Do you agree @hyanwong?

**Comment by hyanwong** [comment]
Yes, just an annoying error message. Unlike the other library issue, I guess we can catch this one and say something sensible?

**Comment by jeromekelleher** [comment]
I'll fix the error message, but otherwise this is behaving exactly as we would expect. (The interpreter exiting gracefully like this with a stack trace is very different to the interpreter crashing out with an abort. The latter is very, very bad.)

**Comment by hyanwong** [comment]
Yes, exactly.
