### ISSUE TITLE
Input file with only singletons fails with Error[-1]

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsinfer#9]
e.g. for a set of position+haplotypes like

895.431856625   0000000100
4083.78325064   0000100000
7224.14894961   0000100000
8235.7370737    0100000000

I get 

```
Traceback (most recent call last):
  File "/home/yan/treeseq-inference/src/run_tsinfer.py", line 76, in <module>
    main()
  File "/home/yan/treeseq-inference/src/run_tsinfer.py", line 65, in main
    num_threads=args.threads)
  File "/home/yan/treeseq-inference/src/../tsinfer/tsinfer/inference.py", line 88, in infer
    genotype_quality=sample_error, path_compression=path_compression)
  File "/home/yan/treeseq-inference/src/../tsinfer/tsinfer/inference.py", line 305, in match_samples
    traceback_file_pattern=traceback_file_pattern)
  File "/home/yan/treeseq-inference/src/../tsinfer/tsinfer/inference.py", line 684, in __init__
    self.restore_tree_sequence_builder(ancestors_ts)
  File "/home/yan/treeseq-inference/src/../tsinfer/tsinfer/inference.py", line 423, in restore_tree_sequence_builder
    edges.child[index])
_tsinfer.LibraryError: Error occured: -1
```

**Comment by jeromekelleher** [comment]
Any input at all should be supported now and reproduced in the output.
